[package]
name = "aether"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
blake3 = "1.8.2"
clap = "4.5.37"
log = "0.4.27"
reqwest = "0.12.15"
serde = "1.0.219"
tokio = "1.44.2"
toml = "0.8.21"
walkdir = "2.5.0"
